import os.path

Import("env")


toolsenv    = env.Clone()

toolsenv.Append( CPPPATH=['#/tools'] )
toolsenv.Append( LIBPATH=['#/lib/${platform}${platformsuffix}/${buildprofile}','#/lib/${platform}${platformsuffix}'] )
toolsenv.Append( LIBS=[ 'network', 'foundation' ] )

if toolsenv['platform'] == 'linux':
	toolsenv.Append( LIBS=[ 'dl', 'rt', 'm' ] )
elif toolsenv['platform'] == 'raspberrypi':
	toolsenv.Append( LIBS=[ 'bcm_host', 'rt', 'm' ] )

#env['netprg'] = toolsenv.Program( 'bin/${buildprofile}/net${prgsuffix}', 'net/main.c' )


# INSTALLS

#toolsenv.AddPostAction( 'bin/${buildprofile}/net${prgsuffix}', toolsenv.Install( '#bin/${platform}${platformsuffix}/${buildprofile}', [ env['netprg'] ] ) )
